require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PicksheetsController do

  # This should return the minimal set of attributes required to create a valid
  # Picksheet. As you add validations to Picksheet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PicksheetsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all picksheets as @picksheets" do
      picksheet = Picksheet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:picksheets).should eq([picksheet])
    end
  end

  describe "GET show" do
    it "assigns the requested picksheet as @picksheet" do
      picksheet = Picksheet.create! valid_attributes
      get :show, {:id => picksheet.to_param}, valid_session
      assigns(:picksheet).should eq(picksheet)
    end
  end

  describe "GET new" do
    it "assigns a new picksheet as @picksheet" do
      get :new, {}, valid_session
      assigns(:picksheet).should be_a_new(Picksheet)
    end
  end

  describe "GET edit" do
    it "assigns the requested picksheet as @picksheet" do
      picksheet = Picksheet.create! valid_attributes
      get :edit, {:id => picksheet.to_param}, valid_session
      assigns(:picksheet).should eq(picksheet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Picksheet" do
        expect {
          post :create, {:picksheet => valid_attributes}, valid_session
        }.to change(Picksheet, :count).by(1)
      end

      it "assigns a newly created picksheet as @picksheet" do
        post :create, {:picksheet => valid_attributes}, valid_session
        assigns(:picksheet).should be_a(Picksheet)
        assigns(:picksheet).should be_persisted
      end

      it "redirects to the created picksheet" do
        post :create, {:picksheet => valid_attributes}, valid_session
        response.should redirect_to(Picksheet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved picksheet as @picksheet" do
        # Trigger the behavior that occurs when invalid params are submitted
        Picksheet.any_instance.stub(:save).and_return(false)
        post :create, {:picksheet => {}}, valid_session
        assigns(:picksheet).should be_a_new(Picksheet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Picksheet.any_instance.stub(:save).and_return(false)
        post :create, {:picksheet => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested picksheet" do
        picksheet = Picksheet.create! valid_attributes
        # Assuming there are no other picksheets in the database, this
        # specifies that the Picksheet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Picksheet.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => picksheet.to_param, :picksheet => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested picksheet as @picksheet" do
        picksheet = Picksheet.create! valid_attributes
        put :update, {:id => picksheet.to_param, :picksheet => valid_attributes}, valid_session
        assigns(:picksheet).should eq(picksheet)
      end

      it "redirects to the picksheet" do
        picksheet = Picksheet.create! valid_attributes
        put :update, {:id => picksheet.to_param, :picksheet => valid_attributes}, valid_session
        response.should redirect_to(picksheet)
      end
    end

    describe "with invalid params" do
      it "assigns the picksheet as @picksheet" do
        picksheet = Picksheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Picksheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => picksheet.to_param, :picksheet => {}}, valid_session
        assigns(:picksheet).should eq(picksheet)
      end

      it "re-renders the 'edit' template" do
        picksheet = Picksheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Picksheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => picksheet.to_param, :picksheet => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested picksheet" do
      picksheet = Picksheet.create! valid_attributes
      expect {
        delete :destroy, {:id => picksheet.to_param}, valid_session
      }.to change(Picksheet, :count).by(-1)
    end

    it "redirects to the picksheets list" do
      picksheet = Picksheet.create! valid_attributes
      delete :destroy, {:id => picksheet.to_param}, valid_session
      response.should redirect_to(picksheets_url)
    end
  end

end
